phrase:
  access_token: 8f5eb58742a259d09fb500a171d0826eb5225a44a48fae1264baa5f249adc778
  project_id: 762985856e5e7d4227c891db72429f73
  file_format: json
  
  push:
    sources:
    - file: pricing_grid.yml
      params:
        file_format: json
        locale_id: en
        autotranslate: true
        update_translations: true
  pull:
    targets:
    - file: cs.json
      params:
        file_format: simple_json
        locale_id: cs
        include_empty_translations: true
    - file: es.json
      params:
        file_format: simple_json
        locale_id: es
        include_empty_translations: true
